services:
  - type: web
    name: PORTFOLIO-LIKITH
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://likith-portfolio.online
      - key: FRONTEND_WWW_URL
        value: https://www.likith-portfolio.online
